<Workspace Version="1.2.1.3083" X="612" Y="376" zoom="1" Name="PlaceScheduleOnSheet" Description="Place schedule on sheet" ID="63b2fc4f-254f-48b6-b1c9-63a746e7eb12" Category="Sasaki">
  <NamespaceResolutionMap />
  <Elements>
    <PythonNodeModels.PythonNode guid="27889e1f-64aa-4a68-8918-33e161ad6b6d" type="PythonNodeModels.PythonNode" nickname="Python Script" x="250" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false" inputcount="3">
      <PortInfo index="0" default="False" />
      <PortInfo index="1" default="False" />
      <PortInfo index="2" default="False" />
      <Script>import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Import RevitNodes
clr.AddReference("RevitNodes")
import Revit
clr.ImportExtensions(Revit.Elements)

# Import Revit elements
from Revit.Elements import *

# Import DocumentManager and TransactionManager
clr.AddReference("RevitServices")
import RevitServices
from RevitServices.Persistence import DocumentManager
from RevitServices.Transactions import TransactionManager

# Import RevitAPI
clr.AddReference("RevitAPI")
import Autodesk
from Autodesk.Revit.DB import *

import System

doc = DocumentManager.Instance.CurrentDBDocument
sheet = IN[0]
sheetId = Autodesk.Revit.DB.ElementId(sheet.Id)
schedule = IN[1]
scheduleId = Autodesk.Revit.DB.ElementId(schedule.Id)
offset = IN[2]
origin = Autodesk.Revit.DB.XYZ(offset.X, offset.Y, offset.Z)

try:
	TransactionManager.Instance.EnsureInTransaction(doc)
	scheduleSheet = ScheduleSheetInstance.Create(doc, sheetId, scheduleId, origin)
	TransactionManager.Instance.TransactionTaskDone()
	OUT = "succeed"
except:
	OUT = "failed"
    </Script>
    </PythonNodeModels.PythonNode>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="03f0ee45-43c2-424e-8a08-f6c95a518418" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="-1" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RevitSheet" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="40e4df1b-72ba-4bda-9b88-3192b877088d" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="0" y="150" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="RevitSchedule" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Symbol guid="6f3f523c-206e-457a-acad-858d2e494924" type="Dynamo.Graph.Nodes.CustomNodes.Symbol" nickname="Input" x="6" y="298" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="True" IsFrozen="false" isPinned="false">
      <Symbol value="ScheduleLocation" />
    </Dynamo.Graph.Nodes.CustomNodes.Symbol>
    <Dynamo.Graph.Nodes.CustomNodes.Output guid="89f2e920-f3aa-4f5c-931b-b815d9b2cb46" type="Dynamo.Graph.Nodes.CustomNodes.Output" nickname="Output" x="447" y="0" isVisible="true" isUpstreamVisible="true" lacing="Disabled" isSelectedInput="False" IsFrozen="false" isPinned="false">
      <PortInfo index="0" default="False" />
      <Symbol value="Status" />
    </Dynamo.Graph.Nodes.CustomNodes.Output>
  </Elements>
  <Connectors>
    <Dynamo.Graph.Connectors.ConnectorModel start="27889e1f-64aa-4a68-8918-33e161ad6b6d" start_index="0" end="89f2e920-f3aa-4f5c-931b-b815d9b2cb46" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="03f0ee45-43c2-424e-8a08-f6c95a518418" start_index="0" end="27889e1f-64aa-4a68-8918-33e161ad6b6d" end_index="0" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="40e4df1b-72ba-4bda-9b88-3192b877088d" start_index="0" end="27889e1f-64aa-4a68-8918-33e161ad6b6d" end_index="1" portType="0" />
    <Dynamo.Graph.Connectors.ConnectorModel start="6f3f523c-206e-457a-acad-858d2e494924" start_index="0" end="27889e1f-64aa-4a68-8918-33e161ad6b6d" end_index="2" portType="0" />
  </Connectors>
  <Notes />
  <Annotations />
  <Presets />
  <Cameras>
    <Camera Name="Background Preview" eyeX="-17" eyeY="24" eyeZ="50" lookX="12" lookY="-13" lookZ="-58" upX="0" upY="1" upZ="0" />
  </Cameras>
</Workspace>